//! Riven.lock file — records exact resolved dependency versions.

use serde::{Deserialize, Serialize};
use std::path::Path;

/// The full lock file structure.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LockFile {
    /// Lock file format version.
    pub version: u32,
    /// Locked pieces.
    #[serde(default, rename = "piece")]
    pub pieces: Vec<LockedPiece>,
}

/// A single locked dependency.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LockedPiece {
    pub name: String,
    pub version: String,
    pub source: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub checksum: Option<String>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub dependencies: Vec<String>,
}

impl LockFile {
    /// Create an empty lock file.
    pub fn new() -> Self {
        Self {
            version: 1,
            pieces: Vec::new(),
        }
    }

    /// Load a lock file from the given directory.
    pub fn load(dir: &Path) -> Result<Self, String> {
        let lock_path = dir.join("Riven.lock");
        if !lock_path.exists() {
            return Err("Riven.lock not found".to_string());
        }
        let content = std::fs::read_to_string(&lock_path)
            .map_err(|e| format!("failed to read Riven.lock: {}", e))?;
        Self::from_str(&content)
    }

    /// Parse a lock file from a string.
    pub fn from_str(s: &str) -> Result<Self, String> {
        toml::from_str(s).map_err(|e| format!("failed to parse Riven.lock: {}", e))
    }

    /// Serialize the lock file to TOML.
    pub fn to_toml_string(&self) -> Result<String, String> {
        let mut output = String::new();
        output.push_str("# This file is auto-generated by `riven`. Do not edit manually.\n");
        output.push_str("# To update, run `riven update`.\n\n");
        output.push_str(&format!("version = {}\n", self.version));

        for piece in &self.pieces {
            output.push('\n');
            output.push_str("[[piece]]\n");
            output.push_str(&format!("name = \"{}\"\n", piece.name));
            output.push_str(&format!("version = \"{}\"\n", piece.version));
            output.push_str(&format!("source = \"{}\"\n", piece.source));
            if let Some(checksum) = &piece.checksum {
                output.push_str(&format!("checksum = \"{}\"\n", checksum));
            }
            if !piece.dependencies.is_empty() {
                let deps: Vec<String> = piece.dependencies.iter().map(|d| format!("\"{}\"", d)).collect();
                output.push_str(&format!("dependencies = [{}]\n", deps.join(", ")));
            }
        }

        Ok(output)
    }

    /// Write the lock file to Riven.lock in the given directory.
    pub fn save(&self, dir: &Path) -> Result<(), String> {
        let content = self.to_toml_string()?;
        let lock_path = dir.join("Riven.lock");
        std::fs::write(&lock_path, content)
            .map_err(|e| format!("failed to write Riven.lock: {}", e))
    }

    /// Find a locked piece by name.
    pub fn find(&self, name: &str) -> Option<&LockedPiece> {
        self.pieces.iter().find(|p| p.name == name)
    }

    /// Check if the lock file is consistent with a manifest.
    ///
    /// Returns `true` if all manifest dependencies are represented in the lock file.
    pub fn is_up_to_date(&self, manifest: &crate::manifest::Manifest) -> bool {
        for dep_name in manifest.dependencies.keys() {
            if self.find(dep_name).is_none() {
                return false;
            }
        }
        // Also check that the lock file doesn't have extra entries
        // that are no longer in the manifest
        for piece in &self.pieces {
            if !manifest.dependencies.contains_key(&piece.name) {
                return false;
            }
        }
        true
    }

    /// Verify checksums of all locked pieces against their fetched sources.
    pub fn verify_checksums(&self, project_dir: &Path) -> Result<(), String> {
        for piece in &self.pieces {
            if let Some(expected) = &piece.checksum {
                // Determine where the source was fetched to
                let dep_dir = project_dir
                    .join("target")
                    .join("deps")
                    .join(&piece.name);

                if dep_dir.exists() {
                    let actual = crate::rlib::hash_sources(&dep_dir)?;
                    if &actual != expected {
                        return Err(format!(
                            "Checksum mismatch for '{}'. Expected {}, got {}. \
                             This may indicate the source has been tampered with.",
                            piece.name, expected, actual
                        ));
                    }
                }
            }
        }
        Ok(())
    }
}

impl Default for LockFile {
    fn default() -> Self {
        Self::new()
    }
}

impl LockedPiece {
    /// Create a locked piece for a path dependency.
    pub fn for_path(name: &str, version: &str, path: &str) -> Self {
        Self {
            name: name.to_string(),
            version: version.to_string(),
            source: format!("path+{}", path),
            checksum: None,
            dependencies: Vec::new(),
        }
    }

    /// Create a locked piece for a git dependency.
    pub fn for_git(name: &str, version: &str, url: &str, rev: &str, checksum: Option<String>) -> Self {
        Self {
            name: name.to_string(),
            version: version.to_string(),
            source: format!("git+{}?rev={}", url, rev),
            checksum,
            dependencies: Vec::new(),
        }
    }

    /// Check if this is a path dependency.
    pub fn is_path(&self) -> bool {
        self.source.starts_with("path+")
    }

    /// Check if this is a git dependency.
    pub fn is_git(&self) -> bool {
        self.source.starts_with("git+")
    }

    /// Extract the path from a path dependency source.
    pub fn path(&self) -> Option<&str> {
        self.source.strip_prefix("path+")
    }

    /// Extract the git URL from a git dependency source.
    pub fn git_url(&self) -> Option<&str> {
        self.source
            .strip_prefix("git+")
            .and_then(|s| s.split('?').next())
    }

    /// Extract the git revision from a git dependency source.
    pub fn git_rev(&self) -> Option<&str> {
        self.source
            .strip_prefix("git+")
            .and_then(|s| s.split("?rev=").nth(1))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_lock_file_roundtrip() {
        let lock = LockFile {
            version: 1,
            pieces: vec![
                LockedPiece {
                    name: "http".to_string(),
                    version: "1.2.5".to_string(),
                    source: "git+https://github.com/user/http.git?rev=abc1234".to_string(),
                    checksum: Some("sha256:a1b2c3d4".to_string()),
                    dependencies: vec![],
                },
                LockedPiece {
                    name: "utils".to_string(),
                    version: "0.3.1".to_string(),
                    source: "git+https://github.com/user/utils.git?rev=def5678".to_string(),
                    checksum: Some("sha256:b2c3d4e5".to_string()),
                    dependencies: vec!["http".to_string()],
                },
                LockedPiece {
                    name: "local-lib".to_string(),
                    version: "0.1.0".to_string(),
                    source: "path+../local_lib".to_string(),
                    checksum: None,
                    dependencies: vec![],
                },
            ],
        };

        let toml_str = lock.to_toml_string().unwrap();
        assert!(toml_str.contains("# This file is auto-generated"));
        assert!(toml_str.contains("version = 1"));

        let reparsed = LockFile::from_str(&toml_str).unwrap();
        assert_eq!(reparsed.version, 1);
        assert_eq!(reparsed.pieces.len(), 3);

        let http = reparsed.find("http").unwrap();
        assert_eq!(http.version, "1.2.5");
        assert!(http.is_git());
        assert_eq!(http.git_url(), Some("https://github.com/user/http.git"));
        assert_eq!(http.git_rev(), Some("abc1234"));

        let utils = reparsed.find("utils").unwrap();
        assert_eq!(utils.dependencies, vec!["http"]);

        let local = reparsed.find("local-lib").unwrap();
        assert!(local.is_path());
        assert_eq!(local.path(), Some("../local_lib"));
        assert!(local.checksum.is_none());
    }

    #[test]
    fn test_locked_piece_constructors() {
        let path_dep = LockedPiece::for_path("utils", "0.1.0", "../utils");
        assert!(path_dep.is_path());
        assert!(!path_dep.is_git());
        assert_eq!(path_dep.path(), Some("../utils"));

        let git_dep = LockedPiece::for_git(
            "http",
            "1.0.0",
            "https://github.com/user/http.git",
            "abc123",
            Some("sha256:deadbeef".to_string()),
        );
        assert!(git_dep.is_git());
        assert!(!git_dep.is_path());
        assert_eq!(git_dep.git_url(), Some("https://github.com/user/http.git"));
        assert_eq!(git_dep.git_rev(), Some("abc123"));
    }

    #[test]
    fn test_empty_lock_file() {
        let lock = LockFile::new();
        let toml_str = lock.to_toml_string().unwrap();
        let reparsed = LockFile::from_str(&toml_str).unwrap();
        assert_eq!(reparsed.version, 1);
        assert!(reparsed.pieces.is_empty());
    }

    #[test]
    fn test_is_up_to_date() {
        use crate::manifest::Manifest;

        let manifest = Manifest::from_str(r#"
[package]
name = "test"
version = "0.1.0"

[dependencies]
http = "1.0.0"
utils = { path = "../utils" }
"#).unwrap();

        // Lock file matching manifest
        let lock = LockFile {
            version: 1,
            pieces: vec![
                LockedPiece::for_path("http", "1.0.0", "..."),
                LockedPiece::for_path("utils", "0.1.0", "../utils"),
            ],
        };
        assert!(lock.is_up_to_date(&manifest));

        // Lock file missing a dep
        let incomplete = LockFile {
            version: 1,
            pieces: vec![
                LockedPiece::for_path("http", "1.0.0", "..."),
            ],
        };
        assert!(!incomplete.is_up_to_date(&manifest));

        // Lock file with extra dep
        let extra = LockFile {
            version: 1,
            pieces: vec![
                LockedPiece::for_path("http", "1.0.0", "..."),
                LockedPiece::for_path("utils", "0.1.0", "../utils"),
                LockedPiece::for_path("orphan", "0.1.0", "..."),
            ],
        };
        assert!(!extra.is_up_to_date(&manifest));
    }
}
